server:
  port: 9002

spring:
  application:
    name: config
  cloud:
    config:
      server:
        native:
#          search-locations: 'file:///C:/Micro Service/KotMicro20220810/app/config'
          search-locations: '/Micro Service/KotMicro20220810/app/config'

    #        git:
    #          uri: https://github.com/happylim99/ConfigServer
    #          default-label: master
    #          username: happylim99@gmail.com
    #          password:
    #          clone-on-start: true
    bus:
      enabled: true
      refresh:
        enabled: true
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

management:
  endpoints:
    web:
      exposure:
        include: bus-refresh

