# version: '2'
# services:
#   rabbitmq:
#     build: .
#     networks:
#       static-network:
#         ipv4_address: 172.17.0.2
# networks:
#   static-network:
#     ipam:
#       config:
#         - subnet: 172.17.0.0/20

version: '3'
services:
  rabbitmq:
      container_name: rabbitmq
      image: "rabbitmq:latest"
      build: .
      ports:
        - "15672:15672"
        - "5672:5672"
        - "15671:15671"
        - "5671:5671"
        - "4369:4369"
      networks:
        spring-network:
            ipv4_address: 172.20.0.2

networks: 
  spring-network: 
    external: true
    # name: spring-network

# networks:
#   spring-network:
#     driver: spring-network
#     ipam:
#       config:
#         - subnet: 172.20.0.0/16
