server:
  port: 9003
  error:
    includeStackTrace: never

eureka:
  client:
    enabled: false
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
#      defaultZone: http://host.docker.internal:9000/eureka
      defaultZone: http://localhost:9000/eureka

spring:
  application:
    name: auth-ws
#  autoconfigure:
#    exclude:
#      - org.springframework.boot.autoconfigure.amqp.RabbitAutoConfiguration
  datasource:
    url: jdbc:mysql://localhost:3306/auth_ws
#    url: jdbc:mysql://host.docker.internal:3306/auth_ws
    username: auth_ws
    password: '@Auth123511'
  jpa:
    hibernate:
      ddlAuto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  cloud:
    bus:
      enabled: false
      refresh:
        enabled: true
  zipkin:
    baseUrl: http://127.0.0.1:9411/
#    baseUrl: http://host.docker.internal:9411/
  boot:
    admin:
      client:
        instance:
          prefer-ip: true
        url: http://127.0.0.1:7999
#        url: http://host.docker.internal:7999
logging:
  file:
    name: /opt/auth-ws.log
#    maxHistory: 20
#    maxSize: 50MB

#  main:
#    allow-bean-definition-overriding: true

#hibernate:
#  enable_lazy_load_no_trans: true

## Security
secret:
  token: secret.token

## gmail
gmail:
  smtp_host: smtp.gmail.com
  smtp_port: 587
  smtp_username: tianhui3010@gmail.com
  smtp_password: gdzdlsmghxsttadm
  smtp_sender: tianhui3010@gmail.com
  smtp_properties:
    mail:
      smtp:
        auth: true
        starttls:
          enable: true

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      showDetails: always

