server:
  port: 9000

spring:
  application:
    name: discovery
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  cloud:
    bus:
      enabled: true
      refresh:
        enabled: true

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:9000/eureka
  instance:
    hostname: localhost
#    leaseRenewalIntervalInSeconds: 30
#  server:
#    enableSelfPreservation: false
